on: push
name: proj ci
jobs:
  proj:
    name: proj
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--features network", "--features bundled_proj", "--features \"bundled_proj network\""]
    container:
      image: georust/proj-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cargo build ${{ matrix.features }}
      - run: cargo test ${{ matrix.features }}

  proj-sys:
    name: proj-sys
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proj-sys
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - container:
              image: "georust/proj-ci:latest"
              env:
                _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC: 1
            features: ""
          - container:
              image: "georust/proj-ci:latest"
              env:
                _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC: 0
            features: "--features bundled_proj"
          - container:
              image: "georust/proj-ci-without-system-proj:latest"
              env:
                _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC: 0
            features: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cargo build ${{ matrix.features }}
      - run: cargo test ${{ matrix.features }}
